### ISSUE TITLE
-d option fails

### ISSUE THREAD

**Issue by pavellishin** [rupa/epub#4]
It tries to access a non-existent screen variable.

```
(venv)[2013-01-04 11:07:03] pavel@addison:~/projects/epub
# ./epub.py -d ~/novel.epub
A Novel
-------




Traceback (most recent call last):
  File "./epub.py", line 362, in <module>
    dump_epub(args.EPUB)
  File "./epub.py", line 178, in dump_epub
    maxcol=screen.getmaxyx()[1]
NameError: global name 'screen' is not defined
(venv)[2013-01-04 11:07:11] pavel@addison:~/projects/epub
```

**Comment by keithstellyes** [comment]
Shouldn't this issue be closed?

**Comment by pavellishin** [comment]
Yes, yes it should.
